package com.bk.automation.runners;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

/**
 * Failed Scenario Rerun Runner.
 * Re-executes only the scenarios that failed in the previous test run.
 *
 * <p>Usage:
 * <pre>
 *   mvn test -Dtest=FailedScenariosRerunRunner
 * </pre>
 *
 * <p>The rerun file is generated by the primary test runners
 * (e.g., rerun:target/rerun/failed_smoke_scenarios.txt)
 */
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "@target/rerun/failed_smoke_scenarios.txt",
        glue = {
                "com.bk.automation.stepdefinitions",
                "com.bk.automation.hooks"
        },
        plugin = {
                "pretty",
                "html:target/reports/cucumber/rerun-report.html",
                "json:target/reports/cucumber/rerun-report.json",
                "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
        },
        monochrome = true,
        dryRun = false
)
public class FailedScenariosRerunRunner {
    // This class re-runs only failed scenarios from the previous test execution.
}
