# ============================================================
# QA Environment Configuration
# ============================================================
//app.url=https://qa.your-healthcare-app.com
app.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
environment=qa
//test.username=qa_admin@healthcare.com
//test.password=QaPassword123
test.username=Admin
test.password=admin123